[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tungstenite = "0.21"
futures-util = { version = "0.3", features = ["sink"] }
tokio-tungstenite = "0.17"
